language: cpp

os:
  - linux

branches:
  only:
    - master

addons:
  sonarqube: true
env:
  global:
    - secure: "QHKyTpaKrpZm6jnoW9MlHo1MokqzK2E+aq8DNH29dNUU5jwWX1G1f1tLf96IgqZNcnJhbF3m9TIGsg8ILjq5f1AHmcr1tN+br5yMcFWpUxxOk3WtcDnHTsv7prQJF24eYJIPWA1E/PdA6KkpRvtVoqnFtYbtojViCFz7WqSrkSgq4831yFU+Kr6hFS5dzA+uLBT6bQrCk8T/01+55yhDn9u+TUy19vvTPY0B4XxDyKzV/VxogmRaYzoYonS2G66334TyHDwPlJEK8ZIQa6TPF0iExi5bytjVE2DRetnBI9Vvqgq+0OtRVPG4uT/WMBIB+iY/5cdLmgPo1kLVZPnPUZHJxMyTdsZkMOZHShAEs1YOahHTzZpO0THc4jraT7eWxMK/Hz+VTDATf9FyWdcGUiwBjZXS9mrSnMsHXDX7zUNXp/m5IcogmZijU3p7+w2otNkQ3OXYVPTj3aQIcMoOhdzXxZtAz5oRMWB+zVUdhnBQTq/a0rrAGQ7bzJlUwUjcaI66p7QtfFlP7Wr/q6YR1TDcThLlrMzG3uzYjGs7yeKNQQBNteWbXGcgBYRFiyDkwKdPnIW78MVqCdvMA8CwUZXJqiA6uxR6c8DOgBMAvDQffRuDfLd/qhJ8m/tgZBch2rlvHB8sdZWhuhCfX6od6M+2uYEZiHU8JFLo2ljRIio=" # defines SONAR_TOKEN=abcdef0123456789

script:
  - sudo update-java-alternatives --set "java-8-oracle"
  - export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  - source /opt/qt55/bin/qt55-env.sh
  - wget http://us.un4seen.com/files/bass24-linux.zip
  - unzip bass24-linux.zip -d bass
  - cp bass/bass.h player/bass.h
  - cp bass/x64/libbass.so player/libbass.so
  - mkdir tmp_dir
  - cd libedah
  - /opt/qt55/bin/qmake
  - build-wrapper-linux-x86-64 --out-dir ../tmp_dir make
  - cd ..
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - cd player
  - /opt/qt55/bin/qmake
  - build-wrapper-linux-x86-64 --out-dir ../tmp_dir make
  - cd ..
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - cd edah
  - /opt/qt55/bin/qmake
  - build-wrapper-linux-x86-64 --out-dir ../tmp_dir make
  - cd ..
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt55base qt55tools libtag1-dev
  - wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip
  - export PATH=$PWD/build-wrapper-linux-x86:$PATH
