language: cpp

os:
  - linux

branches:
  only:
    - master

script:
  - cd edah
  - qmake -qt=qt5
  - make

before_install:
  - sudo add-apt-repository --yes ppa:canonical-qt5-edgers/ubuntu1204-qt5
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
