language: cpp

os:
  - linux

branches:
  only:
    - master

script:
  - cd edah
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt55base qt55tools
